name: webtest
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dhttpd: ^4.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data_table_2: ^2.2.0
  http: ^0.13.1
  shared_preferences: ^2.0.13
  numeric_keyboard: ^1.1.0
  simple_tags: ^0.0.4
  permission_handler: ^8.0.0+2
  numberpicker: ^2.1.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  bloc: ^8.0.0
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  provider: ^6.0.0
  font_awesome_flutter: ^9.2.0
  dropdown_button2: ^1.1.1
  printing: ^5.9.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  freezed: ^1.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
